// Auto-generated by make — do not edit
let buildVersion = "1.0.2"
let buildCommit = "f41b26d"
let buildBranch = "main"
let buildDate = "2026-04-15 01:25:09 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
