// Auto-generated by make — do not edit
let buildVersion = "0.9.17"
let buildCommit = "7ee8c4d"
let buildBranch = "main"
let buildDate = "2026-04-12 11:21:37 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
