// Auto-generated by make — do not edit
let buildVersion = "0.8.6"
let buildCommit = "7618a4c"
let buildBranch = "main"
let buildDate = "2026-04-06 09:56:17 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3"
